### PR TITLE
Fix react playground

### PR DESCRIPTION
**Pull request by mdubus**
Replace Hits with InfiniteHits in the React Playground & fix image style which were overflowing

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]

**Comment by curquiza** [comment]
Should not be merged without @bidoubiwa approval

**Comment by bidoubiwa** [comment]
Wait on #335 as this PR introduces a non working playground until fixed by #335

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
Wait on #335 as this PR introduces a non working playground until fixed by #335

**Comment by bidoubiwa** [comment]
Could you rebase just so we can try if it works correctly with the fix ?

**Review by curquiza — APPROVED** [review]

**Review by bidoubiwa — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
