### PR TITLE
Add missing packages for yarn lint and upgrade all

### PR DESCRIPTION
**Pull request by bb**
Add packages for `yarn lint` and upgrade all packages. Might be fine to merge, if it doesn't break anything for you. It wasn't working for me before the changes either, so I can't test. See #124 for more information about my issues.

### CODE REVIEW

**Comment by bb** [comment]
As most times, the issue was quite obvious in hindsight. Lint was checking all files in node_modules and dist (also those in sub folders like examples/esm) because they were not ignored. The second commit improves that and thus also fixes #124.

**Comment by bb** [comment]
I added another commit which adds missing peer (dev-) dependencies: `@babel/core` and `typescript`.

**Comment by bidoubiwa** [comment]
Awesome! 

Could you add a CI that tests this? You can change `.github/workflows/test.yml` and add the following job: 
```yaml
jobs: 
    style: instant-meilisearch-style-tests
        name: nstant-meilisearch-style-tests
        runs-on: ubuntu-latest
        name: Tests style
        run: yarn lint
```

and inside `./bors.toml`
Change this value:
```toml
status = ["instant-meilisearch-tests"]
```

To this one: 
```toml
status = ["instant-meilisearch-tests", "instant-meilisearch-style-tests"]
```

**Review by bidoubiwa — COMMENTED** [review]
Awesome! 

Could you add a CI that tests this? You can change `.github/workflows/test.yml` and add the following job: 
```yaml
jobs: 
    style: instant-meilisearch-style-tests
        name: nstant-meilisearch-style-tests
        runs-on: ubuntu-latest
        name: Tests style
        run: yarn lint
```

and inside `./bors.toml`
Change this value:
```toml
status = ["instant-meilisearch-tests"]
```

To this one: 
```toml
status = ["instant-meilisearch-tests", "instant-meilisearch-style-tests"]
```

**Comment by bb** [comment]
bors try

**Comment by bb** [comment]
@bidoubiwa I added the changes you requested (with slight syntax changes and added the yarn install step) in the text.yml but it doesn't look like it's running in the branch. I tried to trigger it but got permission denied. Can you please check?

**Comment by bidoubiwa** [comment]
bors try

**Comment by bidoubiwa** [comment]
It seems to be failing because of a merge conflict. Could you [rebase](https://gist.github.com/curquiza/5f7ce615f85331f083cd467fc4e19398)?

**Review by curquiza — DISMISSED** [review]
Your PR is really great @bb! 😁
The merge conflict is indeed due to all the package updates you've done in this PR.

As @bidoubiwa said, you need to rebase and fix the merge conflict at the same time. I don’t know if you are already on [our Slack](https://slack.meilisearch.com/), feel free to joins us, it would be easier to discuss if you need help with the rebase (I’m Clementine). And we also have a #contributions channel if you are interested in MeiliSearch’s tools contributions in general!

**Review by bidoubiwa — APPROVED** [review]

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
