### PR TITLE
Change transform naming to adapt

### PR DESCRIPTION
**Pull request by bidoubiwa**
Adapt is a better word to what instantMeiliSearch does 
image (1)

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]

**Review by curquiza — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors try

**Review by alallema — APPROVED** [review]
LGTM!

**Review by curquiza — APPROVED** [review]
This is time is the good one!

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
