### PR TITLE
Upgrade node version in CI workflows

### LINKED ISSUE #1119: Change node version used in CI from 16 to 18
Most CI jobs are ran with node 16. These should be updated to node 18.

Example: 

https://github.com/meilisearch/instant-meilisearch/blob/bd6ec70211f7a86319a2276cb2abdf89b559ce51/.github/workflows/pre-release-tests.yml#L46-L49

### PR DESCRIPTION
**Pull request by tungbq**
# Pull Request

## Related issue
Fixes #1119 

## What does this PR do?
Upgrade node version in CI workflows (from node 16 to node 18) in following files:
- .github/workflows/meilisearch-prototype-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
Hey! Thanks a lot for this PR :) 

You missed one in this file: https://github.com/meilisearch/instant-meilisearch/blob/main/.github/workflows/publish.yml

**Comment by tungbq** [comment]
> Hey! Thanks a lot for this PR :)
> 
> You missed one in this file: https://github.com/meilisearch/instant-meilisearch/blob/main/.github/workflows/publish.yml

Thanks for reviewing. I got it and updated in the latest commit. Please review again

**Review by warlegend24 — COMMENTED** [review]
hey can you plz tell me how did you made 3 commits in 3 different files and merged them into a single pull request

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
