### PR TITLE
Add support for multiple sort attributes

### LINKED ISSUE #539: SortBy should allow for multiple sort attributes at query time
**Description**
SortBy should allow for multiple sort attributes at query time.

**Basic example**
```js
  instantsearch.widgets.sortBy({
    container: '#sort-by',
    items: [
      { value: 'clothes', label: 'Relevant' }, // default index
      {
        value: 'clothes:price:asc,created_at:desc',
        label: 'Ascending price then descending creation time using query time sort',
      },
    ],
  }),
```

This sort formula is probably not ideal for parsing, it is just an example.

### PR DESCRIPTION
**Pull request by fitimvata**
# Pull Request

I created a new pull request with changes that @bidoubiwa requested in pull request  #1024.

## Related issue
Fixes #539

## What does this PR do?
 - [x] Implement multiple sorting
 - [x] Add tests
 - [x] Update docs

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Incredible contribution 🔥🔥🔥 Thanks a lot.

Could you add a [changeset](https://github.com/meilisearch/instant-meilisearch/blob/main/CONTRIBUTING.md#changesets-) ?

**Comment by fitimvata** [comment]
@bidoubiwa  Done!

**Review by bidoubiwa — COMMENTED** [review]
Thanks for the changeset :) I reviewed your code and its good! Could you also update the sortBy section in the readme by adding some info about this new usage?

**Comment by fitimvata** [comment]
@bidoubiwa I have update the readme.

**Comment by bidoubiwa** [comment]
bors merge

**Comment by fitimvata** [comment]
@bidoubiwa Thanks!

**Pull request merged**
