### PR TITLE
Convert project to TypeScript

### PR DESCRIPTION
**Pull request by curquiza**
The purpose of this PR/branch is to convert this project into a typescript project.
Thanks to @bb for his huge participation in this work!

### CODE REVIEW

**Comment by curquiza** [comment]
Seems like the work is over, tell me if I'm wrong @bidoubiwa! I let you do a final check (with approval) and merge with bors when you are ready 🎉

**Review by bidoubiwa — APPROVED** [review]
Good job @curquiza 😂

**Comment by curquiza** [comment]
I let you decide when merging MY huge work 😂

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
